### ISSUE TITLE
difference to pickle?

### ISSUE THREAD

**Issue by albertz** [numberoverzero/origami#10]
How is it different to pickle? (Pickle's format version 2 is also binary.)

The answer should not simple be answered here but added to the README. It was the first question that came to my mind when reading through the README. It sounded like it does the same thing.

**Comment by numberoverzero** [comment]
Sorry for the slow response.  This is a really good question, and I'll add a section to the readme.

For now, here's the tl;dr:

For transporting basic objects, origami requires significantly less space, even when using pickletools.optimize.  Other dimensions are largely equivalent or in pickle's favor.

Pickle pros:
- **Built-in**: No dependencies
- **Overhead**: Don't need to add anything to existing classes
- **Data types**: Supports a very large superset of the types natively supported by origami
- **Self-contained format.**  Receiver doesn't need to know how to unpack the objects it's accepting.

Pickle cons:
- **Size**: For simple objects, pickle can require nearly two orders of magnitude more space. (This improves significantly as the object grows)
- **Partial data packing**: Origami offers the ability to fold select attributes, when all values aren't needed/ shouldn't be distributed.
- **Multi-format packing**: Related to the previous, origami allows the same class to be folded differently for different consumers.
- **Python-specific format**:  Bitstring's packing format should be easier to translate to other languages.
- **Multiple versions**: Origami has a similar issue, in that it does not make any assumptions about how to pack object type with the data.

**Comment by albertz** [comment]
Note that pickle also supports partial (or just any general) data packing. You can just overwrite the `__getstate__` and `__setstate__` attribute on any class object and it will use those functions if present (in a canonical way).

You are right that pickle also has some problems. It is not perfectly optimized for size.

Also, pickles output is not deterministic. This is mostly because the order of the items in a dict can be different at each run. I patched pickle once to address this (just save dicts ordered) and to extend it (like to be able to save code and function objects and to better find class objects in modules in some cases where pickle fails): [here](https://github.com/albertz/diplom-thesis-math/blob/master/src/utils.py).

How is Origami about the determinism? It would be nice if the same input produces always the same output. (E.g. for diffing and/or in version control.)

Btw., maybe you are interested in this, another slightly related project of me is a binary format for some predefined simple types (lists, dicts, strings, numbers, etc, similar to what JSON and others support): [binstruct](https://github.com/albertz/binstruct). It is able to save numbers of any length and uses [elias gamma coding](https://en.wikipedia.org/wiki/Elias_gamma_coding) for this. This project is also very heavily optimized for size and simplicity and also fast seeking in large binary files.

It wasn't perfectly clear from the README of Origami whether it supports saving numbers of any length at all and what encoding it uses.

**Comment by numberoverzero** [comment]
Good point about get/set state, I missed those entirely.  I think I still prefer using a single string to defining two functions, but they certainly allow more flexibility.

To the point of determinism, I'm not sure how to answer.  Origami is deterministic in that values are always packed in the same order, but relies on both ends knowing the format of those values.  For instance, the following folds a Point object into two bytes, but does not include in the packed format any identifier that two values are present, or the length of those values:

``` python
@pattern()
class Point(object):
    folds = 'x=uint:8, y=uint:8'
    def __init__(self, x=0, y=0):
        self.x, self.y = x, y

p = Point(4, 5)
print fold(p)  # Outputs '\x04\x05'
```

In this way, origami can pack things very tightly, leaving the structural communication up to someone else.  (Basic game packets, for instance, can usually use a single byte prefix).

In researching alternative packing formats I did run into binstruct on pypi.  Although binstruct supports a much wider range of types than origami, I think they're different in their goals.  Origami aims to make the class -> bytestream mapping simple, while binstruct makes the primitive -> compact bytestream mapping simple.  I could see using binstruct as a replacement for bitstring in the future, however.  Especially as a way to expand support to include lists, dictionaries...

I'll add another section to the README explaining what formats and values origami allows - right now the encoding is taken care of by bitstring, which takes the following values: http://pythonhosted.org/bitstring/creation.html#using-the-constructor
